// src/lib/constants.ts
import type { Question } from './types';

export const GPTW_QUESTIONS: Question[] = [
  // Camaraderie (CAM-01 through CAM-08)
  {
    id: 'CAM-01',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Community',
    en: 'I can count on my colleagues to step up and help me when I need it.',
    my: 'အကောင်းဆုံး ကျွန်ုပ်သည် လိုအပ်သောအခါ ကျွန်ုပ်၏ လုပ်ဖော်ကိုင်ဖက်များသည် ကူညီရန် ကြိုးပမ်းမည်ဟု ကျွန်ုပ် ယုံကြည်သည်',
  },
  {
    id: 'CAM-02',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Community',
    en: 'I feel we take the time to celebrate our wins and special events.',
    my: 'ကျောင်းသားများ၏ အောင်မြင်မှုများနှင့် အထူးဖြစ်ရပ်များကို ဂုဏ်ပြုဆင်နွှဲရန် အချိန်ယူကြသည်ဟု ကျွန်ုပ် ခံစားရသည်',
  },
  {
    id: 'CAM-03',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Intimacy',
    en: 'My colleagues care about me as a human being.',
    my: 'လုပ်ဖော်ကိုင်ဖက်များသည် ကျွန်ုပ်ကို လူသားတစ်ဦးအနေဖြင့် ဂရုစိုက်ကြသည်',
  },
  {
    id: 'CAM-04',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Community',
    en: 'I experience great collaboration across different departments, not just within my own area.',
    my: 'ကျွန်ုပ်သည် မိမိဌာနအတွင်းသာမက မတူညီသော ဌာနများအကြား ကောင်းမွန်သော ပူးပေါင်းဆောင်ရွက်မှုကို ကြုံတွေ့ရသည်',
  },
  {
    id: 'CAM-05',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Intimacy',
    en: 'I can be myself around here.',
    my: 'လုပ်ငန်းခွင်တွင် ကျွန်ုပ်သည် မိမိကိုယ်မိမိ ဖြစ်နိုင်သည်',
  },
  {
    id: 'CAM-06',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Intimacy',
    en: 'I feel comfortable approaching my manager or management for an open conversation.',
    my: 'ကျွန်ုပ်သည် မိမိ မန်နေဂျာ သို့မဟုတ် စီမံခန့်ခွဲမှုဆိုင်ရာ ပုဂ္ဂိုလ်များနှင့် ပွင့်လင်းသော စကားပြောဆိုမှုအတွက် ချဉ်းကပ်ရသည်မှာ အဆင်ပြေသည်ဟု ခံစားရသည်',
  },
  {
    id: 'CAM-07',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Hospitality',
    en: 'I felt genuinely welcomed and supported when I joined my current role.',
    my: 'လက်ရှိ တာဝန်တွင် ပါဝင်ခဲ့သောအခါ ကျွန်ုပ်သည် တကယ်ကြိုဆိုလက်ခံကာ ပံ့ပိုးကူညီမှု ရခဲ့သည်ဟု ခံစားခဲ့ရသည်',
  },
  {
    id: 'CAM-08',
    type: 'likert',
    dimension: 'camaraderie',
    subPillar: 'Community',
    en: 'I have fun working here.',
    my: 'ကျွန်ုပ်သည် ဤနေရာတွင် အလုပ်လုပ်ရသည်မှာ ပျော်ရွှင်သည်',
  },

  // Credibility (CRE-09 through CRE-17)
  {
    id: 'CRE-09',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Competence',
    en: 'Our leaders fully embody the best characteristics of our company.',
    my: 'ကျွန်ုပ်တို့၏ ခေါင်းဆောင်များသည် ကုမ္ပဏီ၏ အကောင်းဆုံးသော လက္ခဏာများကို အပြည့်အဝ ကိုယ်ပုံဆောင်ကြသည်',
  },
  {
    id: 'CRE-10',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Integrity',
    en: 'I am led by the people who operate with integrity and keep their promises',
    my: 'ကျွန်ုပ်သည် သမာသမတ်ကျကာ မိမိကတိများကို ထိန်းသိမ်းသည့် ပုဂ္ဂိုလ်များ၏ ဦးဆောင်မှုအောက်တွင် ရှိသည်',
  },
  {
    id: 'CRE-11',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Integrity',
    en: 'I am trusted with responsibility and encouraged to try new things without fear of making honest mistakes.',
    my: 'ကျွန်ုပ်သည် တာဝန်ဝတ္တရားများဖြင့် ယုံကြည်အပ်နှင်းခြင်းခံရပြီး သတိမထားမိဘဲ အမှားများ ဖြစ်မည်ကို ကြောက်ရွံ့မှုမရှိဘဲ အသစ်အဆန်းများ စမ်းသပ်ရန် တိုက်တွန်းနှိုးဆော်ခြင်းခံရသည်',
  },
  {
    id: 'CRE-12',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Communication',
    en: 'I am kept in the loop on important changes and feel safe asking tough questions.',
    my: 'ဆော့ဝဲတွင် အရေးကြီးသောပြောင်းလဲမှုများနှင့် ပတ်သက်၍ ကျွန်ုပ်အား သတင်းပေးရာ၌ ပူးတွဲပါဝင်စေပြီး ခက်ခဲသောမေးခွန်းများ မေးရသည်မှာ ဘေးကင်းသည်ဟု ခံစားရသည်',
  },
  {
    id: 'CRE-13',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Communication',
    en: 'I am clear on the company vision and confident in how the business is being run.',
    my: 'ကျွန်ုပ်သည် ကုမ္ပဏီ၏ မျှော်မှန်းချက်ကို ရှင်းလင်းစွာ နားလည်ပြီး လုပ်ငန်းကို မည်ကဲ့သို့ ဦးဆောင်ပြုလုပ်နေကြောင်းကို ယုံကြည်မှုရှိသည်',
  },
  {
    id: 'CRE-14',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Communication',
    en: 'I am clear about what success looks like in my role.',
    my: 'ကျွန်ုပ်၏ တာဝန်တွင် အောင်မြင်မှု မည်သို့ ဖြစ်သည်ကို ကျွန်ုပ် ရှင်းလင်းစွာ နားလည်သည်',
  },
  {
    id: 'CRE-15',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Competence',
    en: 'I am confident in the talent and character of the people who are hired onto the team.',
    my: 'အဖွဲ့တွင် ငှားရမ်းသောပုဂ္ဂိုလ်များ၏ ပညာရည်နှင့် စရိုက်လက္ခဏာတွင် ကျွန်ုပ် ယုံကြည်မှုရှိသည်',
  },
  {
    id: 'CRE-16',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Integrity',
    en: 'I feel secure in my role and confident in the stability of the company.',
    my: 'ကျွန်ုပ်သည် မိမိ တာဝန်ဝတ္တရားတွင် လုံခြုံမှုရှိသည်ဟု ခံစားပြီး ကုမ္ပဏီ၏ တည်ငြိမ်မှုကို ယုံကြည်မှုရှိသည်',
  },
  {
    id: 'CRE-17',
    type: 'likert',
    dimension: 'credibility',
    subPillar: 'Competence',
    en: 'I feel our teams and resources are organized effectively to get work done without unnecessary friction',
    my: 'မလိုအပ်သော ပွတ်တိုက်မှုများမရှိဘဲ အလုပ်ကို ဆောင်ရွက်နိုင်ရန် ကျွန်ုပ်တို့၏ အဖွဲ့များနှင့် အရင်းအမြစ်များကို ထိရောက်စွာ စီစဉ်ဖွဲ့စည်းထားသည်ဟု ကျွန်ုပ် ခံစားရသည်',
  },

  // Fairness (FAI-18 through FAI-25)
  {
    id: 'FAI-18',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'People here are treated fairly regardless of their gender, race or age.',
    my: 'ဤနေရာတွင် လူများကို ၎င်းတို့၏ လိင်၊ လူမျိုး သို့မဟုတ် အသက်နှင့် မဆိုင်ဘဲ တရားမျှတစွာ ဆက်ဆံကြသည်',
  },
  {
    id: 'FAI-19',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'I am compensated fairly for my work and have access to meaningful benefits.',
    my: 'ကျွန်ုပ်သည် မိမိ အလုပ်အတွက် တရားမျှတသော လစာရရှိပြီး အဓိပ္ပာယ်ရှိသော အကျိုးခံစားခွင့်များကို ရရှိနိုင်သည်',
  },
  {
    id: 'FAI-20',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Impartiality',
    en: 'I feel confident that if I raise a concern, it will be taken seriously and handled fairly.',
    my: 'ကျွန်ုပ်သည် စိုးရိမ်မှုတစ်ခုကို ထောက်ပြပါက ၎င်းကို လေးနက်စွာ သဘောထားကာ တရားမျှတစွာ ကိုင်တွယ်ဖြေရှင်းမည်ဟု ယုံကြည်မှုရှိသည်',
  },
  {
    id: 'FAI-21',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'I receive the same level of support and opportunity from my manager as my peers do.',
    my: 'ကျွန်ုပ်သည် မိမိ မန်နေဂျာထံမှ မိမိ လုပ်ဖော်ကိုင်ဖက်များ ရသည့်နှင့် တူညီသော ပံ့ပိုးမှုနှင့် အခွင့်အလမ်းများကို ရရှိသည်',
  },
  {
    id: 'FAI-22',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'Everyone has an opportunity to get special recognition.',
    my: 'လူတိုင်းသည် အထူးအသိအမှတ်ပြုမှု ရရှိရန် အခွင့်အလမ်းရှိသည်',
  },
  {
    id: 'FAI-23',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'I am treated as a full member here regardless of my position.',
    my: 'ကျွန်ုပ်သည် မိမိ ရာထူးနှင့် မဆိုင်ဘဲ ဤနေရာတွင် အဖွဲ့ဝင် ပြည့်ပြည့်ဝဝတစ်ဦးအဖြစ် ဆက်ဆံခြင်းခံရသည်',
  },
  {
    id: 'FAI-24',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'My workload is reasonable and distributed fairly compared to my peers.',
    my: 'ကျွန်ုပ်၏ လုပ်ငန်းတာဝန်ဝတ္တရားသည် မိမိ လုပ်ဖော်ကိုင်ဖက်များနှင့် နှိုင်းယှဉ်လျှင် မျှတပြီး တရားမျှတစွာ ဖြန့်ဝေထားသည်',
  },
  {
    id: 'FAI-25',
    type: 'likert',
    dimension: 'fairness',
    subPillar: 'Equity',
    en: 'Company policies and rules are enforced consistently across all levels of the organization.',
    my: 'ကုမ္ပဏီ မူဝါဒများနှင့် စည်းမျဉ်းများကို အဖွဲ့အစည်း၏ အဆင့်အားလုံးတွင် တသမတ်တည်း ဆောင်ရွက်ကြသည်',
  },

  // Pride (PRI-26 through PRI-35)
  {
    id: 'PRI-26',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Team/Colleagues',
    en: 'Our customers would rate the service we deliver as "excellent."',
    my: 'ကျွန်ုပ်တို့၏ Customer များသည် ကျွန်ုပ်တို့ ပေးဆောင်သော ဝန်ဆောင်မှုကို "အထူးထူးချွန်" ဟု သတ်မှတ်မည်ဖြစ်သည်',
  },
  {
    id: 'PRI-27',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Personal Job',
    en: 'When I look at what we accomplish, I feel a sense of pride.',
    my: 'ကျွန်ုပ်တို့ ဆောင်ရွက်အောင်မြင်သည်များကို ကြည့်သောအခါ ကျွန်ုပ်သည် ဂုဏ်ယူမှုတစ်ခုကို ခံစားရသည်',
  },
  {
    id: 'PRI-28',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Team/Colleagues',
    en: 'People here quickly adapt to changes needed for our organization\'s success.',
    my: 'ဤနေရာရှိ လူများသည် အဖွဲ့အစည်း၏ အောင်မြင်မှုအတွက် လိုအပ်သော ပြောင်းလဲမှုများနှင့် လျင်မြန်စွာ လိုက်လျောညီထွေဖြစ်ကြသည်',
  },
  {
    id: 'PRI-29',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Personal Job',
    en: 'I want to work here for a long time.',
    my: 'ကျွန်ုပ်သည် ဤနေရာတွင် ကြာကြာ အလုပ်လုပ်လိုသည်',
  },
  {
    id: 'PRI-30',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Personal Job',
    en: 'My work has special meaning: this is not "just a job."',
    my: 'ကျွန်ုပ်၏ အလုပ်တွင် အထူးသဖြင့် အဓိပ္ပာယ်ရှိသည်- ဤသည်မှာ "အလုပ်တစ်ခုသာ" မဟုတ်ပေ',
  },
  {
    id: 'PRI-31',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Company/Organization',
    en: 'I would strongly endorse my company to friends and family as a great place to work.',
    my: 'ကျွန်ုပ်သည် မိမိ ကုမ္ပဏီကို မိတ်ဆွေများနှင့် မိသားစုသို့ အလုပ်လုပ်ရန် ကောင်းမွန်သော နေရာတစ်ခုအဖြစ် အပြည့်အဝ ထောက်ခံအကြံပြုမည်',
  },
  {
    id: 'PRI-32',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Company/Organization',
    en: 'I\'m proud to tell others I work here.',
    my: 'ကျွန်ုပ်သည် ဤနေရာတွင် အလုပ်လုပ်ကြောင်း အခြားသူများကို ပြောရသည်မှာ ဂုဏ်ယူသည်',
  },
  {
    id: 'PRI-33',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Company/Organization',
    en: 'I feel good about the ways we contribute to the community.',
    my: 'ကျွန်ုပ်တို့ ပတ်ဝန်းကျင်အသိုက်အဝန်းကို ပံ့ပိုးကူညီသည့် နည်းလမ်းများနှင့် ပတ်သက်၍ ကျွန်ုပ် ကောင်းသောခံစားချက်ရှိသည်',
  },
  {
    id: 'PRI-34',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Personal Job',
    en: 'I feel I make a difference here.',
    my: 'ကျွန်ုပ်သည် ဤနေရာတွင် ကြောင်ကြောင်ခြားခြား ပြောင်းလဲမှုဖြစ်ပေါ်နိုင်သည်ဟု ခံစားရသည်',
  },
  {
    id: 'PRI-35',
    type: 'likert',
    dimension: 'pride',
    subPillar: 'Team/Colleagues',
    en: 'I would recommend our products and services to family and friends.',
    my: 'ကျွန်ုပ်သည် မိသားစုနှင့် မိတ်ဆွေများသို့ ကျွန်ုပ်တို့၏ ထုတ်ကုန်များနှင့် ဝန်ဆောင်မှုများကို အကြံပြုမည်',
  },

  // Respect (RES-36 through RES-46)
  {
    id: 'RES-36',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Collaboration',
    en: 'I have the tools, resources, and workspace I need to do my best work.',
    my: 'အကောင်းဆုံး အလုပ်လုပ်ရန် ကျွန်ုပ်လိုအပ်သော ကိရိယာများ၊ အရင်းအမြစ်များနှင့် အလုပ်ခွင်နေရာများ ရှိသည်',
  },
  {
    id: 'RES-37',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'I feel appreciated for my work and valued as a person.',
    my: 'ကျွန်ုပ်သည် မိမိ အလုပ်အတွက် တန်ဖိုးထားကြောင်း ခံစားရပြီး လူတစ်ဦးအဖြစ် ဖြင့် အသိအမှတ်ပြုမှုရသည်',
  },
  {
    id: 'RES-38',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Development',
    en: 'I am encouraged to share new ideas, and I am not penalized for making honest mistakes.',
    my: 'ကျွန်ုပ်သည် အသစ်အဆန်းသော စိတ်ကူးများ ဝေမျှရန် တိုက်တွန်းနှိုးဆော်ခြင်းခံရပြီး သတိမထားမိဘဲ အမှားများ ပြုလုပ်သောအတွက် ဒဏ်ခပ်ခြင်းမခံရပေ',
  },
  {
    id: 'RES-39',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'I am provided with benefits that actually add real value to my life.',
    my: 'ကျွန်ုပ်ကို ကျွန်ုပ်၏ ဘဝတွင် တကယ့်တကယ် တန်ဖိုးဖြည့်ပေးသော အကျိုးခံစားခွင့်များ ပေးအပ်ထားသည်',
  },
  {
    id: 'RES-40',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'I am able to take time off from work when I think it\'s necessary.',
    my: 'လိုအပ်သည်ဟု ကျွန်ုပ် ထင်ပါက အလုပ်မှ နားနေချိန် ယူနိုင်သည်',
  },
  {
    id: 'RES-41',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'I am supported in maintaining a healthy balance between my work and personal life.',
    my: 'ကျွန်ုပ်သည် မိမိ အလုပ်နှင့် ကိုယ်ရေးကိုယ်တာ ဘဝကြားတွင် ကျန်းမာသောထမ်းချိန်ညှိမှု ထိန်းသိမ်းရန် ပံ့ပိုးမှုရသည်',
  },
  {
    id: 'RES-42',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Development',
    en: 'I am offered training or development to further myself professionally.',
    my: 'ကျွန်ုပ်ကို ကျွန်ုပ်ကိုယ်တိုင် ပညာရေးအရ တိုးတက်ရန် လေ့ကျင့်ရေး သို့မဟုတ် ဖွံ့ဖြိုးရေးဆိုင်ရာ အခွင့်အလမ်းများ ပေးအပ်ထားသည်',
  },
  {
    id: 'RES-43',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'I feel appreciated and recognized when I put in extra effort.',
    my: 'ကျွန်ုပ်သည် ပိုမိုသော အားထုတ်မှု ပြုသောအခါ တန်ဖိုးထားကြောင်းနှင့် အသိအမှတ်ပြုမှုရသည်ဟု ခံစားရသည်',
  },
  {
    id: 'RES-44',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Collaboration',
    en: 'I am encouraged to try new approaches and feel safe making honest mistakes along the way.',
    my: ' နည်းလမ်းသစ်များ စမ်းသပ်ရန် တိုက်တွန်းနှိုးဆော်ခြင်းခံရပြီး လုပ်ငန်းစဉ်တွင် သတိမထားမိဘဲ အမှားများ ပြုလုပ်ရသည်မှာ ဘေးကင်းသည်ဟု ခံစားရသည်',
  },
  {
    id: 'RES-45',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Collaboration',
    en: 'I am regularly asked for my input, and my ideas are given genuine consideration when I share them.',
    my: 'ကျွန်ုပ်ထံ ပုံမှန်အကြံဉာဏ်များ တောင်းဆိုရပြီး ကျွန်ုပ် ဝေမျှသောအခါ ကျွန်ုပ်၏ စိတ်ကူးများကို တကယ်တမ်း စဉ်းစားပေးသည်',
  },
  {
    id: 'RES-46',
    type: 'likert',
    dimension: 'respect',
    subPillar: 'Caring',
    en: 'This is a psychologically and emotionally healthy place to work.',
    my: 'ဤနေရာသည် စိတ်ပိုင်းဆိုင်ရာနှင့် စိတ်ခံစားချက်ပိုင်းဆိုင်ရာ ကျန်းမာသော အလုပ်လုပ်ရာ နေရာဖြစ်သည်',
  },

  // Uncategorized (UNC-47)
  {
    id: 'UNC-47',
    type: 'likert',
    dimension: 'uncategorized',
    en: 'Taking everything into account, I would say this is a great place to work.',
    my: 'အရာရာကို ထည့်သွင်းစဉ်းစားသောအခါ ဤနေရာသည် အလုပ်လုပ်ရန် အကောင်းဆုံးသောနေရာ ဖြစ်သည်ဟု ကျွန်ုပ် ပြောမည်',
  },
];

export const OPEN_ENDED_QUESTIONS: Question[] = [
  {
    id: 'OE-01',
    type: 'open_ended',
    en: 'Is there anything unique or unusual about this company that makes it a great place to work? Please give specific examples.',
    my: 'ဤကုမ္ပဏီကို ကောင်းမွန်သော အလုပ်လုပ်ရာ နေရာတစ်ခု ဖြစ်စေသော မည်သည့် သာလွန်ကောင်းမွန်သော သို့မဟုတ် ထူးခြားသောအရာ ရှိပါသလား? ကျေးဇူးပြု၍ တိကျသော ဥပမာများ ပေးပါ',
  },
  {
    id: 'OE-02',
    type: 'open_ended',
    en: 'If you could change one thing about this company to make it a better place to work, what would it be?',
    my: 'အကယ်၍ ကုမ္ပဏီကို ပိုမိုကောင်းမွန်သော အလုပ်လုပ်ရာ နေရာတစ်ခု ဖြစ်စေရန် တစ်ခုခုကို ပြောင်းလဲနိုင်ပါက မည်သည့်အရာ ဖြစ်မည်နည်း?',
  },
];

export const DEMOGRAPHIC_FIELDS: Question[] = [
  {
    id: 'DEM-ORG',
    type: 'demographic',
    en: 'My Organization',
    my: 'ကျွန်ုပ်၏ အဖွဲ့အစည်း',
    options: [
      { en: 'Wave Money', my: 'Wave Money' },
      { en: 'Yoma Bank', my: 'ရိုးမဘဏ်' },
    ],
  },
  {
    id: 'DEM-YEAR',
    type: 'demographic',
    en: 'My Service Year',
    my: 'ဝန်ဆောင်မှုနှစ်',
    options: [
      { en: 'Less than 1 year', my: '၁ နှစ်အောက်' },
      { en: '1 to 3 years', my: '၁ မှ ၃ နှစ်' },
      { en: '3 to 5 years', my: '၃ မှ ၅ နှစ်' },
      { en: '5 to 10 years', my: '၅ မှ ၁၀ နှစ်' },
      { en: '10 to 20 years', my: '၁၀ မှ ၂၀ နှစ်' },
      { en: 'More than 20 years', my: '၂၀ နှစ်ကျော်' },
    ],
  },
  {
    id: 'DEM-ROLE',
    type: 'demographic',
    en: 'Which best describes your current role?',
    my: 'သင်၏ လက်ရှိ အခန်းကဏ္ဍကို အကောင်းဆုံး ဖော်ပြသည်မှာ အဘယ်နည်း?',
    options: [
      { en: 'Individual Contributor (I do not manage a team)', my: 'တစ်ဦးချင်း ပံ့ပိုးသူ (ကျွန်ုပ် အဖွဲ့ကို မစီမံဘူး)' },
      { en: 'People Manager (I have direct reports)', my: 'လူများ စီမံသူ (ကျွန်ုပ်တွင် တိုက်ရိုက် အစီရင်ခံသူများ ရှိသည်)' },
    ],
  },
];

// All questions combined — used for form rendering and CSV column generation
export const ALL_QUESTIONS: Question[] = [
  ...GPTW_QUESTIONS,
  ...OPEN_ENDED_QUESTIONS,
  ...DEMOGRAPHIC_FIELDS,
];
